# Created using wingetcreate
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Phieu-Tran.ClipPaste
PackageVersion: 1.2.7
InstallerType: nsis
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Phieu-Tran/ClipPaste/releases/download/v1.2.7/ClipPaste_1.2.7_x64-setup.exe
    InstallerSha256: 932D701ABB7BEC6706FA07264C4CEFC8FD0D317C86EB71CFEA98C4DBCD621101
ManifestType: installer
ManifestVersion: 1.6.0
